steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLottery',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryN',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryAsk',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryAskN',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotterySet',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryUnset',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryLs',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashBench',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}'
  ]
  waitFor: ['-']
