steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--production']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLottery',
    '--source=./src/lottery.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryN',
    '--source=./src/lottery-n.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryAsk',
    '--source=./src/lottery-ask.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryAskN',
    '--source=./src/lottery-ask-n.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotterySet',
    '--source=./src/lottery-set.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryUnset',
    '--source=./src/lottery-unset.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryLs',
    '--source=./src/lottery-ls.js',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=SLACK_TOKEN=${_SLACK_TOKEN}',
    '--region=asia-northeast1'
  ]
  waitFor: ['-']
