steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLottery',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=WEBHOOK_ENDPOINT=${_WEBHOOK_ENDPOINT}'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryN',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=WEBHOOK_ENDPOINT=${_WEBHOOK_ENDPOINT}'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotterySet',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=WEBHOOK_ENDPOINT=${_WEBHOOK_ENDPOINT}'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryUnset',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=WEBHOOK_ENDPOINT=${_WEBHOOK_ENDPOINT}'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'slashLotteryLs',
    '--runtime=nodejs8',
    '--trigger-http',
    '--set-env-vars=WEBHOOK_ENDPOINT=${_WEBHOOK_ENDPOINT}'
  ]
